server.port=8080

ai.base-url=http://ai:8000
ai.summarizer.endpoint=/summarize_json

ai.summarizer.timeout-ms=999999999
ai.timeout.connect-ms=999999999
ai.timeout.response-ms=999999999
ai.timeout.read-secs=999999999
ai.timeout.write-secs=999999999

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://mysql:3306/seosancomplain?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update

app.public-base-url=http://localhost:8080
